GRANT SELECT ON DBA_ROLE_PRIVS TO HOSPITAL_MANAGE;
grant SELECT ON HOSPITAL_MANAGE.CHAMCONG to public;
/
--trigger UPDATE TONGTIEN TRONG HOSPITAL_MANAGE.HOADON KHI INSERT,UPDATE,DELETE TRONG HOSPITAL_MANAGE.CHITIETHD 
CREATE OR REPLACE TRIGGER UPDATE_CTHD_HD 
AFTER INSERT OR UPDATE OR DELETE ON HOSPITAL_MANAGE.CHITIETHD 
REFERENCING OLD AS O NEW AS N
FOR EACH ROW
DECLARE
    SUM_PRICE NUMBER(19, 4):= 0;
BEGIN
    SELECT SUM(DVU.PRICE) into SUM_PRICE FROM HOSPITAL_MANAGE.CHITIETHD CTHD, HOSPITAL_MANAGE.DICHVU DVU WHERE CTHD.MADV = DVU.MADV AND CTHD.SOHD = :N.SOHD;
    UPDATE HOSPITAL_MANAGE.HOADON SET TONGTIEN = SUM_PRICE WHERE SOHD = :N.SOHD;
END;
/
CREATE OR REPLACE PACKAGE EMPLOY_HR_PKG 
AS
 PROCEDURE SET_ROLE_CTX;
 PROCEDURE CLEAR_ROLE_CTX;
END;
/
create or replace context EMPLOYEE_CTX USING HOSPITAL_MANAGE.EMPLOY_HR_PKG;
/
CREATE OR REPLACE PACKAGE BODY HOSPITAL_MANAGE.EMPLOY_HR_PKG
AS 
procedure SET_ROLE_CTX
as
ROLE_GRANTED NVARCHAR2(30);
ID_NHANVIEN  NUMBER(38, 0);
BEGIN
SELECT VAITRO INTO ROLE_GRANTED FROM HOSPITAL_MANAGE.NHANVIEN WHERE MANV = SYS_CONTEXT('USERENV','SESSION_USER');

SELECT MANV INTO ID_NHANVIEN FROM HOSPITAL_MANAGE.NHANVIEN WHERE TO_CHAR(MANV) = SYS_CONTEXT('USERENV', 'SESSION_USER');
DBMS_SESSION.SET_CONTEXT(NAMESPACE=>'EMPLOYEE_CTX', ATTRIBUTE=>'JOB_ROLE',VALUE => ROLE_GRANTED);
DBMS_SESSION.SET_CONTEXT(NAMESPACE=>'EMPLOYEE_CTX', ATTRIBUTE=>'ID_NHANVIEN',VALUE => ID_NHANVIEN);
END SET_ROLE_CTX;

procedure CLEAR_ROLE_CTX
as
begin
DBMS_SESSION.CLEAR_CONTEXT(NAMESPACE=>'EMPLOYEE_CTX', ATTRIBUTE=>'JOB_ROLE');
DBMS_SESSION.CLEAR_CONTEXT(NAMESPACE=>'EMPLOYEE_CTX', ATTRIBUTE=>'ID_NHANVIEN');
end CLEAR_ROLE_CTX;
end;
/
CREATE OR REPLACE TRIGGER SET_ROLE_USERS
AFTER LOGON ON DATABASE
BEGIN
    HOSPITAL_MANAGE.EMPLOY_HR_PKG.SET_ROLE_CTX;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN NULL;
END;
/
--BACSI CHI CO THE xem thong tin BN do minh chiu trach nhiem
CREATE OR REPLACE FUNCTION HOSPITAL_MANAGE.TREATMENT_DOCTOR_ONLY(P_SCHEMA IN VARCHAR2 DEFAULT NULL, P_OBJECT IN VARCHAR2 DEFAULT NULL)
RETURN VARCHAR2
AS
BEGIN
if (sys_context('EMPLOYEE_CTX', 'JOB_ROLE') != 'Bác s?') then 
return ' ';
else
RETURN 'MABS = SYS_CONTEXT(''EMPLOYEE_CTX'', ''ID_NHANVIEN'')';
end if;
END;
/
DROP VIEW HOSPITAL_MANAGE.BACSI_BENHNHAN;
CREATE VIEW HOSPITAL_MANAGE.BACSI_BENHNHAN AS
SELECT hsbn.mabs, hsbn.mabn, hsbn.makb, hsbn.ngaykham, hsbn.tinhtrang, hsbn.ketluan, hsdv.madv, hsdv.ngay AS NGAY_TH, hsdv.nguoi_th, ctdt.mathuoc, ctdt.lieudung, ctdt.sl FROM hospital_manage.HOSOBN hsbn, HOSPITAL_MANAGE.chitietdonthuoc ctdt, HOSPITAL_MANAGE.hoso_dichvu hsdv
where hsbn.makb = ctdt.makb and hsbn.makb = hsdv.makb;
grant select, insert,update on hospital_manage.bacsi_benhnhan to bacsi;
/
execute dbms_rls.drop_policy('HOSPITAL_MANAGE', 'BACSI_BENHNHAN','treatment_doctor_only');
EXECUTE dbms_rls.add_policy ('HOSPITAL_MANAGE', 'BACSI_BENHNHAN','treatment_doctor_only','HOSPITAL_MANAGE', 'TREATMENT_DOCTOR_ONLY', 'SELECT,INSERT,UPDATE', TRUE);
/
CREATE OR REPLACE FUNCTION HOSPITAL_MANAGE.EMPLOYEE_SELF_CHAMCONG_ONLY(P_SCHEMA IN VARCHAR2 DEFAULT NULL, P_OBJECT IN VARCHAR2 DEFAULT NULL)
RETURN VARCHAR2
AS
BEGIN
RETURN 'MANV = SYS_CONTEXT(''EMPLOYEE_CTX'', ''ID_NHANVIEN'')';
END;
/
EXECUTE dbms_rls.drop_policy ('HOSPITAL_MANAGE', 'CHAMCONG','SELF_CHAMCONG_only');
EXECUTE dbms_rls.add_policy ('HOSPITAL_MANAGE', 'CHAMCONG','SELF_CHAMCONG_only','HOSPITAL_MANAGE', 'EMPLOYEE_SELF_CHAMCONG_ONLY', 'SELECT');
/
GRANT SELECT ON HOSPITAL_MANAGE.BACSI_BENHNHAN TO BACSI;
grant select on hospital_manage.thuoc to bacsi;
grant select, insert, update on hospital_manage.chitietdonthuoc to bacsi; 
/
CREATE OR REPLACE FUNCTION HOSPITAL_MANAGE.doctor_modify_thuoc_ONLY(P_SCHEMA IN VARCHAR2 DEFAULT NULL, P_OBJECT IN VARCHAR2 DEFAULT NULL)
RETURN VARCHAR2
as
begin
IF (sys_context('EMPLOYEE_CTX', 'JOB_ROLE') != 'Bác s?') THEN
    RETURN '';
    ELSE
return 'MAKB IN (SELECT MAKB FROM HOSPITAL_MANAGE.HOSOBN WHERE MABS = SYS_CONTEXT(''EMPLOYEE_CTX'', ''ID_NHANVIEN''))';
END IF;
end;
/
GRANT SELECT ON HOSPITAL_MANAGE.benhnhan_dichvu_tt TO BACSI;
/
EXECUTE dbms_rls.DROP_policy('HOSPITAL_MANAGE', 'benhnhan_dichvu_tt', 'DOCOTR_DICHVU')
execute dbms_rls.add_policy('HOSPITAL_MANAGE', 'benhnhan_dichvu_tt', 'DOCOTR_DICHVU', 'HOSPITAL_MANAGE', 'DOCTOR_MODIFY_THUOC_ONLY','SELECT');
/
execute DBMS_RLS.DROP_POLICY('HOSPITAL_MANAGE','CHITIETDONTHUOC','DOCTOR_MODIFY_THUOC');
EXECUTE DBMS_RLS.ADD_POLICY('HOSPITAL_MANAGE','CHITIETDONTHUOC','DOCTOR_MODIFY_THUOC','HOSPITAL_MANAGE','doctor_modify_thuoc_ONLY','SELECT,UPDATE,INSERT',TRUE);
/
EXECUTE dbms_rls.DROP_policy('HOSPITAL_MANAGE', 'HOSO_DICHVU', 'DOCTOR_DICHVU_BN')
execute dbms_rls.add_policy('HOSPITAL_MANAGE', 'HOSO_DICHVU', 'DOCTOR_DICHVU_BN', 'HOSPITAL_MANAGE', 'DOCTOR_MODIFY_THUOC_ONLY','SELECT,UPDATE,INSERT',TRUE);
/
create or replace view hospital_manage.temp_hsbn_doctor as select * from hospital_manage.hosobn;
CREATE OR REPLACE FUNCTION HOSPITAL_MANAGE.doctor_modify_hobn_treatmentonly(P_SCHEMA IN VARCHAR2 DEFAULT NULL, P_OBJECT IN VARCHAR2 DEFAULT NULL)
RETURN VARCHAR2
as
begin
IF (sys_context('EMPLOYEE_CTX', 'JOB_ROLE') != 'Bác s?') THEN
    RETURN '';
    ELSE
return 'MABS = SYS_CONTEXT(''EMPLOYEE_CTX'', ''ID_NHANVIEN'')';
END IF;
end;
/
grant select, update on hospital_manage.temp_hsbn_doctor to bacsi;
/
EXECUTE dbms_rls.DROP_policy('HOSPITAL_MANAGE', 'temp_hsbn_doctor', 'DOCTOR_HOSOBN');
execute dbms_rls.add_policy('HOSPITAL_MANAGE', 'temp_hsbn_doctor', 'DOCTOR_HOSOBN', 'HOSPITAL_MANAGE', 'doctor_modify_hobn_treatmentonly','SELECT,UPDATE,INSERT',TRUE);

/
select * from hospital_manage.hosobn WHERE MABS = 66;
CREATE USER "66" IDENTIFIED BY "1111";
GRANT BACSI TO "66";
GRANT CREATE SESSION TO "66";
commit;
/
