--------------------------------------------------------
--  File created - Monday-June-28-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table NHANVIEN
--------------------------------------------------------

  CREATE TABLE "HOSPITAL_MANAGE"."NHANVIEN" 
   (	"MANV" NUMBER(*,0), 
	"HOTEN" NVARCHAR2(100), 
	"LUONG" NUMBER(19,4), 
	"VAITRO" NVARCHAR2(200), 
	"DONVI" NUMBER(*,0), 
	"OLS_NHANVIEN" NUMBER(10,0) DEFAULT NULL
   )
REM INSERTING into HOSPITAL_MANAGE.NHANVIEN
SET DEFINE OFF;
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (1,'TTrần Văn Ơn',30000000,'Tổng Giám đốc',1,410);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (2,'NNguyễn Trường Giang',29800000,'Giám đốc chi nhánh',1,311);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (3,'QQuách Ngọc Luyến',29600000,'Giám đốc chi nhánh',2,312);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (4,'?Đào Thị Hường',29400000,'Giám đốc chi nhánh',3,313);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (5,'TTrần Thị Kim Anh',29200000,'Quản lí TNNS',1,201);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (6,'NNguyễn Thị Oanh',29000000,'Quản lí TV',1,201);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (7,'LLâm Thị Nga',28800000,'Quản lí CM',1,201);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (8,'NNguyễn Thị Bích Thuỳ',28600000,'Quản lí TNNS',1,201);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (9,'?Đặng Thu Hiền',28400000,'Quản lí TV',1,201);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (10,'Đào Thị Huyền Trang',28200000,'Quản lí TNNS',2,202);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (11,'Nguyễn Ngọc Thắng',28000000,'Quản lí TV',2,202);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (12,'Nguyễn Anh Trung',27800000,'Quản lí TV',2,202);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (13,'Nguyễn Tường Liên',27600000,'Quản lí CM',2,202);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (14,'Lê Ngọc Thưởng',27400000,'Quản lí CM',2,202);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (15,'Phòng Kinh doanh',27200000,'Quản lí CM',2,202);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (16,'Đỗ Anh Vũ',27000000,'Quản lí TNNS',3,203);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (17,'Đinh Anh Tuấn',26800000,'Quản lí TNNS',3,203);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (18,'Nguyễn Thế Cường',26600000,'Quản lí TV',3,203);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (19,'Trần Thị Nhường',26400000,'Quản lí TV',3,203);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (20,'Lê Thị Dung',26200000,'Quản lí CM',3,203);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (21,'Tăng Thị Nhung',26000000,'Quản lí CM',3,203);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (22,'Vũ Thị Thuỳ Anh',25800000,'Điều phối',1,201);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (23,'Hoàng Mạnh Hùng',25600000,'Điều phối',1,201);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (24,'Bùi Bích Phương',25400000,'Điều phối',2,202);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (25,'Nguyễn Kiều Nga',25200000,'Điều phối',2,202);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (26,'Lê Liên Hương',25000000,'Điều phối',3,203);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (27,'Nguyễn Thị Trang',24800000,'Điều phối',3,203);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (28,'Nguyễn Thu Trang',24600000,'NV tài vụ',1,201);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (29,'Cao Thị Phượng',24400000,'NV tài vụ',1,201);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (30,'Nguyễn Hương Giang',24200000,'NV tài vụ',2,202);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (31,'Nguyễn Thị Bích Hạnh',24000000,'NV tài vụ',2,202);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (32,'Nguyễn Thị Thơm',23800000,'NV tài vụ',3,203);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (33,'Nguyễn Thị Minh Loan',23600000,'NV tài vụ',3,203);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (34,'Nguyễn Trường Giang',23400000,'Bác sĩ',1,201);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (35,'Vũ An Phượng',23200000,'Bác sĩ',1,201);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (36,'Nguyễn Thị Minh Phương',23000000,'Bác sĩ',1,201);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (37,'Lưu Vân Anh',22800000,'Bác sĩ',1,201);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (38,'Phạm Thị Thu',22600000,'Bác sĩ',1,201);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (39,'Hoàng Thị Huê',22400000,'Bác sĩ',1,201);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (40,'Dương Thị Đào',22200000,'Bác sĩ',1,201);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (41,'Diêm Thị Oanh',22000000,'Bác sĩ',1,201);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (42,'Bùi Thu Hoài',21800000,'Bác sĩ',1,201);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (43,'Vũ Thị Tố Uyển',21600000,'Bác sĩ',1,201);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (44,'Phạm Đình Quyết',21400000,'Bác sĩ',1,201);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (45,'Nguyễn Thị Tuyết Hoa',21200000,'Bác sĩ',1,201);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (46,'Nguyễn Thị Thu Hiền',21000000,'Bác sĩ',1,201);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (47,'Nguyễn Thị Như',20800000,'Bác sĩ',1,201);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (48,'Lê Thị Bích Thuỷ',20600000,'Bác sĩ',1,201);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (49,'Tạ Thị Hiền',20400000,'Bác sĩ',1,201);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (50,'Lê Thị Thu Hiền',20200000,'Bác sĩ',1,201);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (51,'Trần Thị Giang',20000000,'Bác sĩ',1,201);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (52,'Nguyễn Thị Lâm',19800000,'Bác sĩ',1,201);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (53,'Nguyễn Hồng Mai',19600000,'Bác sĩ',1,201);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (54,'Phạm Thị Mỹ Hạnh',19400000,'Bác sĩ',1,201);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (55,'Hồ Thị Cẩm Vân',19200000,'Bác sĩ',2,202);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (56,'Vũ Sỹ Luân',19000000,'Bác sĩ',2,202);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (57,'Trần Tuấn Mười',18800000,'Bác sĩ',2,202);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (58,'Lê Thị Duyên',18600000,'Bác sĩ',2,202);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (59,'Đoàn Thị Thuy',18400000,'Bác sĩ',2,202);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (60,'Phạm Thị Thuỷ',18200000,'Bác sĩ',2,202);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (61,'Lê Phương Thảo',18000000,'Bác sĩ',2,202);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (62,'Ngô Văn Nam',17800000,'Bác sĩ',2,202);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (63,'Nguyễn Thị Năm',17600000,'Bác sĩ',2,202);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (64,'Phạm Vũ Oai',17400000,'Bác sĩ',2,202);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (65,'Trần Khắc Hùng',17200000,'Bác sĩ',2,202);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (66,'Nguyễn Thị Minh Thu',17000000,'Bác sĩ',2,202);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (67,'Nguyễn Thị Hồng',16800000,'Bác sĩ',2,202);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (68,'Nguyễn Thị Thanh',16600000,'Bác sĩ',2,202);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (69,'Phạm Thị Kềng',16400000,'Bác sĩ',2,202);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (70,'Nguyễn Thị Thuý Hạnh',16200000,'Bác sĩ',2,202);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (71,'Vũ Thị Sáo',16000000,'Bác sĩ',3,203);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (72,'Ngô Thị Phúc',15800000,'Bác sĩ',3,203);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (73,'Nguyễn Thị Đường',15600000,'Bác sĩ',3,203);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (74,'Hoàng Sỹ Đường',15400000,'Bác sĩ',3,203);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (75,'Nguyễn Hiền Lương',15200000,'Bác sĩ',3,203);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (76,'Phạm Thị Hồng Hạnh',15000000,'Bác sĩ',3,203);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (77,'Nguyễn Thị Thu Hoàn',14800000,'Bác sĩ',3,203);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (78,'Dương Thị Thanh Phương',14600000,'Bác sĩ',3,203);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (79,'Phạm Thu Hương',14400000,'Bác sĩ',3,203);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (80,'Trần Thị Mai Hương',14200000,'Bác sĩ',3,203);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (81,'Nguyễn Văn Huy',14000000,'NV bán thuốc',1,201);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (82,'Đỗ Thị Quế',13800000,'NV bán thuốc',1,201);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (83,'Nguyễn Hồng Hạnh',13600000,'NV bán thuốc',1,201);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (84,'Trần Thị Thúy Hương',13400000,'NV bán thuốc',1,201);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (85,'Lê Quang Anh',13200000,'NV bán thuốc',2,202);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (86,'Lương Minh Đức',13000000,'NV bán thuốc',2,202);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (87,'Nguyễn Thị Thu Thuỷ',12800000,'NV bán thuốc',2,202);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (88,'Hoàng Thị Thảo',12600000,'NV bán thuốc',2,202);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (89,'Phạm Văn Tuấn',12400000,'NV bán thuốc',3,203);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (90,'Trần Văn Tiến',12200000,'NV bán thuốc',3,203);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (91,'Đào Hải Long',12000000,'NV bán thuốc',3,203);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (92,'Vũ Thị Chung',11800000,'NV bán thuốc',3,203);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (93,'Nguyễn Thúy Vui',11600000,'NV Kế toán',1,201);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (94,'Nguyễn Bá Kế',11400000,'NV Kế toán',1,201);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (95,'Ứng Việt Tùng',11200000,'NV Kế toán',1,201);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (96,'Nguyễn Công Y',11000000,'NV Kế toán',2,202);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (97,'Nguyễn Thị Vân Xuyên',10800000,'NV Kế toán',2,202);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (98,'Mai Thị My',10600000,'NV Kế toán',3,203);
Insert into HOSPITAL_MANAGE.NHANVIEN (MANV,HOTEN,LUONG,VAITRO,DONVI,OLS_NHANVIEN) values (99,'Nguyễn Thị Lan Anh',10400000,'NV Kế toán',3,203);
--------------------------------------------------------
--  DDL for Index SYS_C007459
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSPITAL_MANAGE"."SYS_C007459" ON "HOSPITAL_MANAGE"."NHANVIEN" ("MANV")
--------------------------------------------------------
--  Constraints for Table NHANVIEN
--------------------------------------------------------

  ALTER TABLE "HOSPITAL_MANAGE"."NHANVIEN" ADD PRIMARY KEY ("MANV")
  USING INDEX  ENABLE
--------------------------------------------------------
--  Ref Constraints for Table NHANVIEN
--------------------------------------------------------

  ALTER TABLE "HOSPITAL_MANAGE"."NHANVIEN" ADD CONSTRAINT "NV_DV_FK" FOREIGN KEY ("DONVI")
	  REFERENCES "HOSPITAL_MANAGE"."DONVI" ("MADV") ENABLE

--------------------------------------------------------
--  File created - Monday-June-28-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DONVI
--------------------------------------------------------

  CREATE TABLE "HOSPITAL_MANAGE"."DONVI" 
   (	"MADV" NUMBER(*,0), 
	"TEN" NVARCHAR2(150)
   ) ;
REM INSERTING into HOSPITAL_MANAGE.DONVI
SET DEFINE OFF;
Insert into HOSPITAL_MANAGE.DONVI (MADV,TEN) values (1,'Quận 1');
Insert into HOSPITAL_MANAGE.DONVI (MADV,TEN) values (2,'Quận 2');
Insert into HOSPITAL_MANAGE.DONVI (MADV,TEN) values (3,'Quận 3');
--------------------------------------------------------
--  DDL for Index SYS_C007460
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSPITAL_MANAGE"."SYS_C007460" ON "HOSPITAL_MANAGE"."DONVI" ("MADV") 
  ;
--------------------------------------------------------
--  Constraints for Table DONVI
--------------------------------------------------------

  ALTER TABLE "HOSPITAL_MANAGE"."DONVI" ADD PRIMARY KEY ("MADV")
  USING INDEX  ENABLE;
